HW3 Seletskaya
ok-technopolis-autumn-2022/Alisa_Seletskaya pull request #3
Opened 2022-11-17 12:52 UTC by sealisaa

Настроила SCSS (файл styles.css сгенерирован IDE из styles.scss) и добавила parcel

2022-11-17 13:08 UTC, fromanywhere requested changes

2022-11-17 13:08 UTC, fromanywhere commented on index.html
> +    <link href="style/styles.css" rel="stylesheet" />
так не интересно. Здесь должна быть ссылка на scss файл, и parcel её должен сам наживую переваривать в css

2022-11-17 13:09 UTC, fromanywhere commented on index.html
> +    <link href="style/styles.css" rel="stylesheet" />
кстати, результат компиляции класть в репозиторий никогда не надо

2022-11-17 15:49 UTC, sealisaa commented on index.html
> +    <link href="style/styles.css" rel="stylesheet" />
Поправила, теперь parcel сам обрабатывает SCSS

2022-11-18 07:59 UTC, fromanywhere approved these changes

2022-11-18 09:01 UTC, merged